name: CI Pipeline
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

  Clippy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features -- -D warnings

    - name: Run clippy
      run: cargo clippy --all-features -- -D warnings

  Fmt:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Fmt check
      run: cargo fmt -- --check

  Tests:
    needs: [Build, Fmt]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build tests
      run: cargo test --verbose --no-run

    - name: Run tests
      run: cargo test --verbose --no-fail-fast -- --test-threads=1

  Coverage:
    needs: [Tests]
    runs-on: ubuntu-latest
    steps:

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        directory: ./coverage/
        fail_ci_if_error: true
        files: lcov.info
        flags: unittests
        name: github-codecov


