[package]
name = "yos-probdts"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
getrandom = { version = "0.2.3" }
siphasher = "0.3.7"
